name: dart_multipart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  microsoft_kiota_bundle: ^0.0.4
  microsoft_kiota_abstractions: ^0.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
