openapi: 3.0.0
info:
  title: Upload Service
  version: 0.0.0
paths:
  /upload:
    post:
      operationId: uploadFile
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/userUpload'
components:
  schemas:
    userType:
      type: string
      enum:
        - Unset
        - User
        - Visitor
    userUpload:
      type: object
      properties:
        file:
          type: string
          format: binary
        description:
          type: string
        userId:
          type: integer
          format: int32
        userType:
          $ref: '#/components/schemas/userType'
      required:
        - file
        - userType
